weights: weights/cutie-base-mega.pth

# exp_id: default
# dataset: d17-val
# amp: false
# output_dir: null
max_internal_size: -1
flip_aug: false
# json_directory: null
size: 480
# save_all: true
# use_all_masks: false
use_long_term: false
mem_every: 5
max_mem_frames: 5
long_term:
  count_usage: true
  max_mem_frames: 10
  min_mem_frames: 5
  num_prototypes: 128
  max_num_tokens: 10000
  buffer_tokens: 2000
top_k: 30
stagger_updates: 5
chunk_size: -1
save_aux: false
# save_scores: false
# visualize: false

model:
  pixel_mean:
    - 0.485
    - 0.456
    - 0.406
  pixel_std:
    - 0.229
    - 0.224
    - 0.225
  pixel_dim: 256
  key_dim: 64
  value_dim: 256
  sensory_dim: 256
  embed_dim: &model_embed_dim 256
  pixel_encoder:
    type: resnet50
    ms_dims:
      - 1024
      - 512
      - 256
  mask_encoder:
    type: resnet18
    final_dim: 256
  pixel_pe_scale: 32
  pixel_pe_temperature: 128
  object_transformer:
    embed_dim: *model_embed_dim
    ff_dim: 2048
    num_heads: 8
    num_blocks: 3
    num_queries: &num_queries 16
    read_from_pixel:
      input_norm: false
      input_add_pe: false
      add_pe_to_qkv:
        - true
        - true
        - false
    read_from_past:
      add_pe_to_qkv:
        - true
        - true
        - false
    read_from_memory:
      add_pe_to_qkv:
        - true
        - true
        - false
    read_from_query:
      add_pe_to_qkv:
        - true
        - true
        - false
      output_norm: false
    query_self_attention:
      add_pe_to_qkv:
        - true
        - true
        - false
    pixel_self_attention:
      add_pe_to_qkv:
        - true
        - true
        - false
  object_summarizer:
    embed_dim: *model_embed_dim
    num_summaries: *num_queries
    add_pe: true
  aux_loss:
    sensory:
      enabled: true
      weight: 0.01
    query:
      enabled: true
      weight: 0.01
  mask_decoder:
    up_dims:
      - 256
      - 128
      - 128
